import { buttonVariants } from "@/components/ui/button";

const buttonGhostXs = buttonVariants({ variant: "ghost", size: "xs" });
const buttonGhostIconXs = buttonVariants({ variant: "ghost", size: "icon-xs" });
const copyButtonMarker = "docs-snippet-copy docs-code-copy";
const codeRuntimeClasses = [
  "dark:[&_span[style]]:![color:var(--shiki-dark,var(--shiki-light,currentColor))]",
  "dark:[&_span[style]]:![font-style:var(--shiki-dark-font-style,var(--shiki-light-font-style,inherit))]",
  "dark:[&_span[style]]:![font-weight:var(--shiki-dark-font-weight,var(--shiki-light-font-weight,inherit))]",
  "dark:[&_span[style]]:![text-decoration:var(--shiki-dark-text-decoration,var(--shiki-light-text-decoration,inherit))]",
  "[&_.conum]:ml-1",
  "[&_.conum]:inline-flex",
  "[&_.conum]:h-[1.05rem]",
  "[&_.conum]:w-[1.05rem]",
  "[&_.conum]:items-center",
  "[&_.conum]:justify-center",
  "[&_.conum]:rounded-full",
  "[&_.conum]:[border:1px_solid_color-mix(in_oklab,var(--code-foreground)_82%,var(--code))]",
  "[&_.conum]:bg-code-foreground",
  "[&_.conum]:![color:var(--code)]",
  "[&_.conum]:[font-family:var(--shell-font)]",
  "[&_.conum]:text-[0.68rem]",
  "[&_.conum]:leading-none",
  "[&_.conum]:font-bold",
  "[&_.conum]:not-italic",
  "[&_.conum]:align-[0.08em]",
  "[&_.conum::before]:content-[attr(data-value)]"
].join(" ");
const calloutFooterRuntimeClasses = [
  "[&_ol]:grid",
  "[&_ol]:gap-[0.35rem]",
  "[&_ol]:!m-0",
  "[&_ol]:!p-0",
  "[&_ol]:list-none",
  "[&_ol]:[counter-reset:docs-code-callout]",
  "[&_li]:grid",
  "[&_li]:grid-cols-[auto_minmax(0,1fr)]",
  "[&_li]:items-start",
  "[&_li]:gap-[0.7rem]",
  "[&_li]:[counter-increment:docs-code-callout]",
  "[&_li+li]:!mt-0",
  "[&_li::before]:mt-[0.2rem]",
  "[&_li::before]:inline-flex",
  "[&_li::before]:h-[1.15rem]",
  "[&_li::before]:w-[1.15rem]",
  "[&_li::before]:items-center",
  "[&_li::before]:justify-center",
  "[&_li::before]:rounded-full",
  "[&_li::before]:[border:1px_solid_color-mix(in_oklab,var(--code-foreground)_82%,var(--code))]",
  "[&_li::before]:bg-code-foreground",
  "[&_li::before]:text-code",
  "[&_li::before]:text-[0.72rem]",
  "[&_li::before]:leading-none",
  "[&_li::before]:font-bold",
  "[&_li::before]:content-[counter(docs-code-callout)]",
  "[&_table]:w-full",
  "[&_table]:border-collapse",
  "[&_td]:align-top",
  "[&_td:first-child]:w-[1.15rem]",
  "[&_td:first-child]:pr-[0.7rem]",
  "[&_td:first-child]:pt-[0.2rem]",
  "[&_td:first-child_.conum]:ml-0",
  "[&_td:first-child_.conum]:inline-flex",
  "[&_td:first-child_.conum]:h-[1.15rem]",
  "[&_td:first-child_.conum]:w-[1.15rem]",
  "[&_td:first-child_.conum]:items-center",
  "[&_td:first-child_.conum]:justify-center",
  "[&_td:first-child_.conum]:rounded-full",
  "[&_td:first-child_.conum]:[border:1px_solid_color-mix(in_oklab,var(--code-foreground)_82%,var(--code))]",
  "[&_td:first-child_.conum]:bg-code-foreground",
  "[&_td:first-child_.conum]:text-code",
  "[&_td:first-child_.conum]:[font-family:var(--shell-font)]",
  "[&_td:first-child_.conum]:text-[0.72rem]",
  "[&_td:first-child_.conum]:leading-none",
  "[&_td:first-child_.conum]:font-bold",
  "[&_td:first-child_.conum]:not-italic",
  "[&_td:first-child_.conum::before]:content-[attr(data-value)]",
  "[&_td:first-child_.conum+b]:hidden",
  "[&_p]:!m-0"
].join(" ");
const propertiesTableRuntimeClasses = [
  "[&_table.tableblock]:w-full",
  "[&_table.tableblock]:!m-0",
  "[&_table.tableblock]:border-collapse",
  "[&_table.tableblock]:text-[0.92rem]",
  "[&_table.tableblock]:leading-[1.45]",
  "[&_table.tableblock_caption]:!m-0",
  "[&_table.tableblock_caption]:text-left",
  "[&_table.tableblock_caption]:font-bold",
  "[&_table.tableblock_caption]:text-foreground",
  "[&_table.tableblock_:where(th,td)]:border",
  "[&_table.tableblock_:where(th,td)]:border-border",
  "[&_table.tableblock_:where(th,td)]:px-3",
  "[&_table.tableblock_:where(th,td)]:py-[0.65rem]",
  "[&_table.tableblock_:where(th,td)]:align-top",
  "[&_table.tableblock_th]:bg-muted",
  "[&_table.tableblock_th]:font-bold",
  "[&_table.tableblock_th]:text-foreground"
].join(" ");

export const docsSnippetStyles = {
  card: "docs-snippet-template docs-code-block my-5 flex flex-col gap-0 overflow-hidden rounded-xl border border-code-border bg-code-tab py-0 text-code-foreground shadow-sm shadow-black/[0.03] dark:shadow-black/20",
  cardWithFooter: "docs-code-block-with-footer",
  standaloneCard: "docs-code-block docs-snippet-card my-5 flex flex-col gap-0 overflow-hidden rounded-xl border border-code-border bg-code-tab py-0 text-code-foreground shadow-sm shadow-black/[0.03] dark:shadow-black/20",
  propertiesCard: "docs-properties-template my-5 flex flex-col gap-0 overflow-hidden rounded-xl border border-border bg-card py-0 text-card-foreground shadow-sm shadow-black/[0.03] dark:shadow-black/20",
  codeSnippetTemplate: "docs-code-snippet-template",
  dependencySnippetTemplate: "docs-properties-template docs-dependency-template",
  toolbarHeader: "docs-code-toolbar docs-snippet-card-header !flex min-h-10 items-center justify-between gap-3 border-b border-code-border bg-code-tab px-3 py-2 [.border-b]:!pb-2",
  textHeader: "@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 border-b border-code-border bg-code-tab px-4 py-2.5 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:!pb-2.5",
  cardAction: "col-start-2 row-span-2 row-start-1 self-start justify-self-end",
  toolbarAction: "ml-auto self-center justify-self-auto",
  content: "docs-snippet-panels overflow-hidden bg-code px-0 text-code-foreground",
  panel: "docs-code-content docs-snippet-card-content bg-code text-code-foreground",
  codePre: "shiki shiki-themes github-light-default github-dark-default !m-0 !max-w-full !overflow-x-auto !rounded-none !border-0 !bg-code !px-6 !py-4 text-sm !leading-6 !text-code-foreground",
  codeElement: `shiki-code grid min-w-max font-mono !text-[0.85rem] !leading-6 [&_.line]:min-h-[1.5rem] ${codeRuntimeClasses}`,
  footer: `docs-snippet-card-footer docs-code-callouts block border-t border-code-border bg-code-tab px-6 py-3 text-sm leading-5 text-code-foreground [&_code]:!rounded-none [&_code]:!bg-code-foreground/10 [&_code]:!p-0 [&_code]:!text-[1em] [&_code]:!leading-[inherit] [&_code]:!text-code-foreground ${calloutFooterRuntimeClasses}`,
  heading: "docs-snippet-heading flex min-w-0 items-center gap-2 text-sm leading-5 font-semibold text-code-foreground",
  propertiesHeading: "docs-properties-heading flex min-w-0 items-center gap-2 text-sm leading-5 font-semibold",
  description: "docs-snippet-description text-xs leading-5 text-code-muted",
  propertiesDescription: "docs-properties-description text-xs leading-5",
  propertiesAnchor: "docs-properties-anchor block h-0 overflow-hidden no-underline",
  propertiesCount: "docs-properties-count inline-flex w-fit shrink-0 items-center justify-center gap-1 overflow-hidden rounded-full border border-transparent bg-secondary px-2.5 py-1 text-[0.78rem] font-medium whitespace-nowrap text-secondary-foreground",
  propertiesScroll: `docs-properties-scroll overflow-x-auto px-0 ${propertiesTableRuntimeClasses}`,
  actions: "docs-snippet-actions flex flex-wrap items-center justify-start justify-self-start gap-2",
  tabs: "docs-snippet-tabs docs-code-tabs docs-code-tabs-multi flex flex-wrap items-center gap-1",
  externalHeader: "docs-snippet-external-header my-0 mt-[1.35rem] mb-[0.45rem]",
  externalTitle: "title docs-snippet-external-title my-0 mt-[1.35rem] mb-[0.45rem] text-[0.95rem] leading-[1.45] font-bold text-foreground [overflow-wrap:anywhere] [&_code]:whitespace-normal",
  externalHeaderTitle: "docs-snippet-external-header-title my-0 text-[0.95rem] leading-[1.45] font-bold text-foreground [overflow-wrap:anywhere] [&_code]:whitespace-normal",
  externalHeaderDescription: "docs-snippet-external-header-description mt-1 text-sm leading-6 text-muted-foreground",
  copyButtonMarker,
  copyButton: `${copyButtonMarker} ${buttonGhostIconXs} text-code-muted hover:bg-code-border hover:text-code-foreground dark:hover:bg-code-border`,
  buttonGhostXs,
  buttonGhostIconXs,
  languageButton: "docs-code-language language-option inline-flex h-6 items-center gap-1 align-middle leading-none text-code-muted aria-selected:font-semibold aria-selected:text-code-foreground",
  languageButtonActive: "selected font-semibold text-code-foreground",
  languageButtonInactive: "text-code-muted",
  staticLanguage: "docs-code-language docs-code-language-static inline-flex h-6 shrink-0 items-center justify-center gap-1 rounded-md px-2 text-xs leading-none font-medium whitespace-nowrap text-code-muted",
  languageText: "docs-code-language-text inline-flex items-center leading-none",
  languageTextSelector: ".docs-code-language-text",
  languageIcon: "docs-code-language-icon inline-flex size-3.5 shrink-0 items-center justify-center self-center leading-none [&_svg]:block [&_svg]:size-full",
  languageImageIcon: "docs-code-language-icon block size-3.5 shrink-0 self-center align-middle dark:brightness-0 dark:invert",
  languageIconFill: "docs-code-language-icon-fill",
  kindIcon: "docs-snippet-kind-icon"
};
